_target_: src.datamodules.classification_datamodule.ClassificationDataModule

dataset_name: "adult"
data_dir: ${paths.data_dir} # data_dir is specified in config.yaml
batch_size: 64
test_batch_size: 128
train_val_test_split: [0.7, 0.1, 0.2]
num_workers: 0
pin_memory: False
